### ISSUE TITLE
[스트리밍]v4l2->dash

### ISSUE THREAD

**Issue by alifeunfolds** [DaewoongP/cerule-stream#10]
- [x] V4L2 설치 및 설정
- [x] ffmpeg 설치 (하드웨어 가속화)
    - [x] 빌드 툴 설치
- [x] Nginx 설치 및 설정
    - [x] nginx.conf 
- [ ] 문서화

**Comment by leejihown** [comment]
동영상 포맷과 코덱의 종류와 활용을 조사하고 스트리밍의 전체적인 연결과 구조를 알아보았습니다. 이미지나 설명을 정리하고 있습니다.

**Comment by leejihown** [comment]
대단
http://bluexmas.tistory.com/446

**Comment by DaewoongP** [comment]
[라즈베리파이3B ffmpeg 하드웨어 가속](http://nbspcrop.blogspot.com/2018/04/3b-ffmpeg.html)

**Comment by alifeunfolds** [comment]
ffmpeg 4.0.1
nginx 1.14.0
으로 설치해주세요

**Comment by alifeunfolds** [comment]
nginx 같이 설치해야 모듈
- upstream(built-in)
- [rtmp](https://github.com/arut/nginx-rtmp-module)
- http_ssl_module (openssl 라이브러리 필요)

**Comment by alifeunfolds** [comment]
[ffmpeg 하드웨어 가속화 정보](https://trac.ffmpeg.org/wiki/HWAccelIntro)

**Comment by leejihown** [comment]
[uv4l 설치법](http://www.linux-projects.org/uv4l/installation/)

**Comment by alifeunfolds** [comment]
[uv4l ffmpeg](https://www.linux-projects.org/uv4l/tutorials/ffmpeg/)

**Comment by DaewoongP** [comment]
[mmap : 디바이스 오류 해결방법](https://github.com/ccrisan/motioneye/issues/489)

**Comment by alifeunfolds** [comment]
[nginx rtmp module API](https://github.com/arut/nginx-rtmp-module/wiki/Directives#rtmp)

**Comment by alifeunfolds** [comment]
nginx.conf
rtmp>server directive
```
  application webcam {
            live on;

            # Stream from local webcam
            exec_static ffmpeg -f video4linux2 -i /dev/video0 -c:v libx264 -an
                               -f flv rtmp://localhost:1935/webcam/mystream;
        }
```

**Comment by alifeunfolds** [comment]
[MPEG-TS](https://en.wikipedia.org/wiki/MPEG_transport_stream)

**Comment by alifeunfolds** [comment]
replace nginx-rtmp-module with [/sergey-dryabzhinsky/nginx-rtmp-module](https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/commits/dev)

**Comment by alifeunfolds** [comment]
ffmpeg와 nginx 옵션 최적화 필요.

**Comment by leejihown** [comment]
http://bigcode.tistory.com/1
