### ISSUE TITLE
[안드로이드] 빌드, 배포 자동화

### ISSUE THREAD

**Issue by alifeunfolds** [DaewoongP/cerule-stream#12]
- [ ] apk sign key 발급
- [ ] 빌드 자동화
- [ ] 배포 자동화

**Comment by alifeunfolds** [comment]
- [안드로이드 앱을 빠르고 지속적으로 전달하기](https://academy.realm.io/kr/posts/continuous-delivery-for-android/)
- [Buddybuild 적용기](https://sikeeoh.github.io/2017/08/25/lookpin-android-buddybuild/)
- [CircleCI를 사용한 지속적 통합](https://www.androidhuman.com/lecture/quality/2016/10/03/android_quality_part1_circleci/)
- [Bitrise로 안드로이드 배포 자동화하기 1) Bitrise + Integrations = ❤️](http://www.junil.kim/bitrise/)
- [Travis로 안드로이드 배포하기(CD)](https://calyfactory.github.io/android-slack-deploy/)
- [안드로이드와 자동화 툴](https://www.theteams.kr/teams/859/post/64917)

**Comment by DaewoongP** [comment]
[안드로이드 developer guide](https://developer.android.com/guide/)

**Comment by alifeunfolds** [comment]
[fabric.io](https://fabric.io)
-  [fastlane](https://fastlane.tools/)을 빌드툴로 사용함
- [fabric 배포 방법](https://www.fabric.io/features/distribution)
- [fastlane 사용법 ](https://docs.fastlane.tools/getting-started/android/setup/)
