### ISSUE TITLE
[서버]라즈베리파이 카메라 센서

### ISSUE THREAD

**Issue by DaewoongP** [DaewoongP/cerule-stream#18]
코덱과 해상도가 인식률에 미치는 정도를 파악하기 위함.
- [x] 라즈베리파이로 테스트 동영상을 저장
    - 1분, 680x480, 1280x720
    - raw, avi, h263, h264
- [ ] 서버에서 인식률 확인

**Comment by leejihown** [comment]
ffmpeg로 h264 코덱으로 해상도 조절후 1분 촬영해서 저장후 보내기

**Comment by alifeunfolds** [comment]
raspivid raw video 생성
```
raspivid -w 320 -h 240 -t 30000 -td 1000,1000 --raw raw -rf rgb -o foo
```
[참조](https://www.raspberrypi.org/forums/viewtopic.php?t=189830)

**Comment by DaewoongP** [comment]
[raspberry pi cam](http://picamera.readthedocs.io/en/release-1.12/index.html)

encoder > pi raw video encoder check

**Comment by leejihown** [comment]
https://github.com/HIFLY-CSM/HIFLY-Final

**Comment by leejihown** [comment]
우선 rawvideo로 코덱하는것이 색상 옵션이 설정되지 않아서 처음 찍었을때 플래이 했을때 흑백 화면으로 거의 야간 화면 같은 화면이라 함들어서 색상 옵션을 했습니다. 
![색상 옵션 리스트](https://user-images.githubusercontent.com/40731434/42734970-1382a23c-883c-11e8-9dc8-2f6229105bf8.PNG)

**Comment by alifeunfolds** [comment]
```
ffmpeg -i test2_640x480.avi -s 1280x720 test2_1280x720.avi
```
1. 640x480 -> 1280x720으로 업샘플링을 하는 것보다 1280x720 -> 640x480으로 다운샘플링하는게 손실이 더 적을 것 같은데 맞나요? 

2. 업샘플링은 바이리니어2d 알고리즘을 사용할 것 같고 다운 샘플링은 maxpool 알고리즘을 사용할 것같은데  다운샘플링이 더 빠른 걸로 알고 있어요. 조사해보고 다음에 할 때는 더 빠른 걸로 사용해 주세요 :)

3. 오브젝트 디텍션 모델이 분석을 할때 rgb 포맷을 사용 하므로, yuv 포맷으로 영상정보를 받으면 openCV에서 내부적으로 yuv포맷을 rgb포맷으로 바꿔야 합니다. 참조된 색상 변환 리스트를 보면 rgb를 지원하는 것으로 나오는데 어떤 방식으로 컬러포맷을 인코딩하는게 빠르게 되나요?
[RGB와 YUV 포맷](http://imagej.tistory.com/150)

**Comment by leejihown** [comment]
http://stonerain.tistory.com/54
http://ianccani.tistory.com/entry/imgconvert-swsscale

**Comment by alifeunfolds** [comment]
[Video Formats, Codecs and Containers (Explained)](https://www.youtube.com/watch?v=XvoW-bwIeyY)

**Comment by alifeunfolds** [comment]
[ffmpeg 속도 향상](https://stackoverflow.com/questions/36422211/processing-camera-stream-in-opencv-pushing-it-over-rtmp-nginx-rtmp-module-usi)

**Comment by leejihown** [comment]
[h264 코덱에서 재생시 시간이 안나오는 오류 시 해결법](https://video.stackexchange.com/questions/20367/ffmpeg-mxf-mp4-cannot-get-proper-audio-on-output-file)

**Comment by alifeunfolds** [comment]
[ffmpeg 설치 및 간단한 명령어](https://m.blog.naver.com/PostView.nhn?blogId=chandong83&logNo=220851288433&proxyReferer=http%3A%2F%2Fwww.google.co.kr%2Furl%3Fsa%3Dt%26rct%3Dj%26q%3D%26esrc%3Ds%26source%3Dweb%26cd%3D1%26ved%3D0ahUKEwjkqfaQhpHcAhXVdt4KHW9lCxkQFgglMAA%26url%3Dhttp%253A%252F%252Fm.blog.naver.com%252Fchandong83%252F220851288433%26usg%3DAOvVaw2_QzkAzldLQy4elTkaUhRS)

[라즈베리파이3B ffmpeg 하드웨어 가속](http://nbspcrop.blogspot.com/2018/04/3b-ffmpeg.html)

[ffmpeg 하드웨어 가속화 플랫폼 별 정보](https://trac.ffmpeg.org/wiki/HWAccelIntro)

[v4l2의 간단한 정의와 설치법](http://www.rasplay.org/?p=6257)

[v4l2와 ffmpeg를 이용한 카메라 캡처](https://trac.ffmpeg.org/wiki/Capture/Webcam)

ffmpeg와 v4l2가 제대로 구동하는지 확인하였다면 아래 명령어로 동영상을 찍고 플레이어로 확인
ffmpeg -f v4l2 -framerate 30 -video_size 640x480 -i /dev/video0 output.mkv

오류 해결 방법 
[mmap : 디바이스 오류 해결방법](https://github.com/ccrisan/motioneye/issues/489)
