### ISSUE TITLE
[스트리밍]전송 코덱 비교

### ISSUE THREAD

**Issue by DaewoongP** [DaewoongP/cerule-stream#19]
디바이스에서 서버로 보내는 영상의 압축 속도와 전송 속도를 비교하기 위해서 진행.
- [x] Raw, xvid, h263 H264 코덱 차이점 분석
- [x] 코덱별 압축률, 압축 속도, 전송 속도 비교

[LEAD Video Codecs의 비교표](http://www.hyubwoo.com/product/leadtech/enduser/videocodec/compare_body.htm)

**Comment by DaewoongP** [comment]
위의 코덱 비교표 활용하셔서 h264 활용 x 또는 직접 보내는 방식으로 변경 부탁드립니다!

**Comment by leejihown** [comment]
http://blog.naver.com/PostView.nhn?blogId=josm17&logNo=220601051707

**Comment by leejihown** [comment]
링크와 추가적인 코덱 리스트를 찾아 가장 효율적인 코덱 비교 자료를 정리 하고 정하겠습니다.

**Comment by DaewoongP** [comment]
[raw vs h264](https://www.youtube.com/watch?v=yZgtMZNGr6g)

**Comment by DaewoongP** [comment]
"
$ ffmpeg -formats
"
